#!/usr/bin/env bash
# bootstrap-mgmt.sh — OpenKubes Management Cluster Bootstrap
# Generated by ok-cluster from templates/talos-mgmt/bootstrap-mgmt.sh.tpl
#
# This script installs the full OpenKubes management stack on ok-mgmt:
#   1. Crossplane
#   2. Crossplane Providers (kubernetes, helm)
#   3. Crossplane Functions (patch-and-transform, go-templating)
#   4. CAPI core + Talos + selected infrastructure provider (via clusterctl)
#   5. Provider-specific infra preparation (providers/<provider>/provider-infra.sh)
#   6. XRDs + Compositions (from openkubes/openkubes)
#   7. RBAC for Crossplane provider ServiceAccounts
#   8. OpenWebUI XRD + Composition (platform/ai)
#   8b. OpenClaw XRD + Composition (platform/ai)
#   8c. OpenRMF XRD + Composition + Role (platform/robotics)
#
# Run after: make bootstrap CLUSTER=ok-mgmt
# Context:   KUBECONFIG must point to the management cluster
#
# Infrastructure provider is selected by the Implementation Profile
# (cluster-config.yaml `provider:`) — rendered here as INFRA_PROVIDER=kubevirt.
#
# See: ok-cluster ADR-Platform-008 — TYPE=talos-mgmt
#      ok-cluster ADR-Platform-007 — CAPI responsibility split
#      OK-106 — CAPO as second infrastructure-provider consumer (Proof A: provider selection)

set -euo pipefail

CLUSTER_NAME="${CLUSTER_NAME:-ok-mgmt}"
KUBECONFIG_PATH="${KUBECONFIG:-$HOME/.kube/ok-mgmt.yaml}"
OPENKUBES_REPO="${OPENKUBES_PATH:-$(dirname "$0")/../../openkubes}"
INFRA_PROVIDER="kubevirt"

log()  { echo "[mgmt-bootstrap] $*"; }
ok()   { echo "[mgmt-bootstrap] ✅ $*"; }
fail() { echo "[mgmt-bootstrap] ❌ $*" >&2; exit 1; }

export KUBECONFIG="$KUBECONFIG_PATH"

log "Bootstrapping OpenKubes management stack on cluster 'ok-mgmt' (provider: $INFRA_PROVIDER)..."
log "KUBECONFIG: $KUBECONFIG_PATH"
echo ""

# ── Verify cluster is reachable ───────────────────────────────────────────────
log "Verifying cluster connectivity..."
kubectl get nodes || fail "Cannot reach management cluster — check KUBECONFIG"
ok "Cluster reachable"
echo ""

# ── Step 1: Crossplane ────────────────────────────────────────────────────────
log "Step 1: Installing Crossplane..."
helm repo add crossplane-stable https://charts.crossplane.io/stable 2>/dev/null || true
helm repo update crossplane-stable

helm upgrade --install crossplane crossplane-stable/crossplane \
  --namespace crossplane-system \
  --create-namespace \
  --wait \
  --timeout 300s

ok "Crossplane installed (version: $(helm list -n crossplane-system -o json | python3 -c 'import sys,json; print(json.load(sys.stdin)[0]["app_version"])' 2>/dev/null || echo 'unknown'))"
echo ""

# ── Step 2: Crossplane Providers ──────────────────────────────────────────────
log "Step 2: Installing Crossplane Providers (kubernetes, helm)..."

kubectl apply -f - <<YAML
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-contrib-provider-kubernetes
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.14.1
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-contrib-provider-helm
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.19.0
YAML

log "Waiting for providers to become healthy..."
kubectl wait provider.pkg.crossplane.io/crossplane-contrib-provider-kubernetes \
  --for=condition=Healthy --timeout=300s
kubectl wait provider.pkg.crossplane.io/crossplane-contrib-provider-helm \
  --for=condition=Healthy --timeout=300s

ok "Providers installed and healthy"
echo ""

# ── Step 3: Crossplane Functions ──────────────────────────────────────────────
log "Step 3: Installing Crossplane Functions..."

kubectl apply -f - <<YAML
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.9.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-go-templating
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.9.0
YAML

log "Waiting for functions to become healthy..."
kubectl wait function/function-patch-and-transform \
  --for=condition=Healthy --timeout=300s
kubectl wait function/function-go-templating \
  --for=condition=Healthy --timeout=300s

ok "Functions installed and healthy"
echo ""

# ── Step 4: CAPI core + Talos + selected infrastructure provider ──────────────
# Provider selection is driven by the Implementation Profile. INFRA_PROVIDER is
# substituted at render time (kubevirt|openstack). The provider-specific controller
# wait and infrastructure preparation live in providers/<provider>/provider-infra.sh
# (Step 5), keeping this file provider-neutral except for the --infrastructure flag.
log "Step 4: Installing CAPI providers (core, talos, $INFRA_PROVIDER)..."

clusterctl init \
  --infrastructure kubevirt \
  --bootstrap talos \
  --control-plane talos

log "Waiting for provider-neutral CAPI pods to be ready..."
kubectl wait deployment/capi-controller-manager \
  -n capi-system --for=condition=Available --timeout=300s
kubectl wait deployment/cacppt-controller-manager \
  -n cacppt-system --for=condition=Available --timeout=300s

ok "CAPI core + Talos control-plane providers installed"
echo ""

# ── Step 5: provider-specific controller wait + infrastructure preparation ────
# Sourced from the rendered provider profile. Runs in this shell (set -euo and the
# log/ok/fail helpers are inherited). CAPK prepares the external-infra kubeconfig
# secret; CAPO asserts OpenStack credentials. See providers/<provider>/provider-infra.sh.
log "Step 5: Provider-specific infrastructure preparation ($INFRA_PROVIDER)..."
source "$(dirname "$0")/provider-infra.sh"
echo ""

# ── Step 6: XRDs + Compositions + RBAC ────────────────────────────────────────
log "Step 6: Applying OpenKubes platform contracts (XRDs, Compositions, RBAC)..."

PLATFORM_DIR="${OPENKUBES_REPO}/platform/cluster-management"

if [[ ! -d "$PLATFORM_DIR" ]]; then
  fail "openkubes/openkubes not found at $OPENKUBES_REPO — set OPENKUBES_PATH"
fi

kubectl apply -f "$PLATFORM_DIR/crossplane/namespace.yaml"
kubectl apply -f "$PLATFORM_DIR/crossplane/rbac.yaml"
kubectl apply -f "$PLATFORM_DIR/crossplane/xrd.yaml"
kubectl apply -f "$PLATFORM_DIR/crossplane/xrd-cleanup.yaml"
kubectl apply -f "$PLATFORM_DIR/crossplane/xrd-upgrade.yaml"
kubectl apply -f "$PLATFORM_DIR/crossplane/composition.yaml"
kubectl apply -f "$PLATFORM_DIR/crossplane/composition-cleanup.yaml"
kubectl apply -f "$PLATFORM_DIR/crossplane/composition-upgrade.yaml"

ok "Platform contracts applied"
echo ""

# ── Step 7: RBAC for Crossplane provider ServiceAccounts ──────────────────────
log "Step 7: Configuring RBAC for Crossplane provider..."

# Resolve the dynamic ServiceAccount name for provider-kubernetes
PROVIDER_SA=$(kubectl get serviceaccount -n crossplane-system \
  -o jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | \
  grep "crossplane-contrib-provider-kubernetes" | head -1)

if [[ -z "$PROVIDER_SA" ]]; then
  fail "Cannot find provider-kubernetes ServiceAccount in crossplane-system"
fi

log "Provider ServiceAccount: $PROVIDER_SA"

kubectl apply -f - <<YAML
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-provider-kubernetes-jobs
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps", "serviceaccounts"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-provider-kubernetes-jobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-provider-kubernetes-jobs
subjects:
  - kind: ServiceAccount
    name: $PROVIDER_SA
    namespace: crossplane-system
YAML

# ProviderConfig for in-cluster access
kubectl apply -f - <<YAML
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: in-cluster
spec:
  credentials:
    source: InjectedIdentity
YAML

ok "RBAC configured"
echo ""

# ── Step 8: OpenWebUI XRD + Composition ──────────────────────────────────────
log "Step 8: Applying OpenWebUI platform contracts (XRD, Composition)..."

OPENKUBES_AI_DIR="${OPENKUBES_REPO}/platform/ai/open-webui/crossplane"

if [[ ! -d "$OPENKUBES_AI_DIR" ]]; then
  log "WARNING: platform/ai not found at $OPENKUBES_AI_DIR — skipping OpenWebUI setup"
else
  kubectl apply -f "$OPENKUBES_AI_DIR/xrd.yaml"
  kubectl apply -f "$OPENKUBES_AI_DIR/composition.yaml"

  kubectl wait xrd/openwebuiinstances.platform.openkubes.ai \
    --for=condition=Established --timeout=60s

  ok "OpenWebUI XRD + Composition ready on ok-mgmt"
  log "  Deploy with: kubectl apply -f platform/ai/open-webui/crossplane/examples/<cluster>.yaml"
fi
echo ""

# ── Step 8b: OpenClaw XRD + Composition ──────────────────────────────────────
log "Step 8b: Applying OpenClaw platform contracts (XRD, Composition)..."

OPENKUBES_OPENCLAW_DIR="${OPENKUBES_REPO}/platform/ai/openclaw/crossplane"

if [[ ! -d "$OPENKUBES_OPENCLAW_DIR" ]]; then
  log "WARNING: platform/ai/openclaw not found at $OPENKUBES_OPENCLAW_DIR — skipping OpenClaw setup"
else
  kubectl apply -f "$OPENKUBES_OPENCLAW_DIR/xrd.yaml"
  kubectl apply -f "$OPENKUBES_OPENCLAW_DIR/composition.yaml"

  kubectl wait xrd/openclawinstances.platform.openkubes.ai \
    --for=condition=Established --timeout=60s

  ok "OpenClaw XRD + Composition ready on ok-mgmt"
  log "  Deploy with: kubectl apply -f platform/ai/openclaw/crossplane/examples/<cluster>.yaml"
fi
echo ""

# ── Step 8c: OpenRMF XRD + Composition + Role ─────────────────────────────────
log "Step 8c: Applying OpenRMF platform contracts (XRD, Composition, Role)..."

OPENKUBES_OPENRMF_DIR="${OPENKUBES_REPO}/platform/robotics/open-rmf/crossplane"

if [[ ! -d "$OPENKUBES_OPENRMF_DIR" ]]; then
  log "WARNING: platform/robotics/open-rmf not found at $OPENKUBES_OPENRMF_DIR — skipping OpenRMF setup"
else
  kubectl apply -f "$OPENKUBES_OPENRMF_DIR/xrd.yaml"
  kubectl apply -f "$OPENKUBES_OPENRMF_DIR/composition.yaml"
  kubectl apply -f "$OPENKUBES_OPENRMF_DIR/rbac/claim-editor-role.yaml"

  kubectl wait xrd/openrmfinstances.platform.openkubes.ai \
    --for=condition=Established --timeout=60s

  ok "OpenRMF XRD + Composition + Role ready on ok-mgmt"
  log "  NOTE: rmf-credentials Secret in crossplane-system must be created separately before applying a Claim"
  log "  Deploy with: kubectl apply -f platform/robotics/open-rmf/crossplane/examples/<cluster>.yaml"
fi
echo ""

# ── Done ──────────────────────────────────────────────────────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ok "Management cluster 'ok-mgmt' is fully operational!"
echo ""
echo "  Crossplane:      $(kubectl get deployment crossplane -n crossplane-system -o jsonpath='{.status.readyReplicas}')/1 ready"
echo "  CAPI providers:  $(kubectl get deployments -A --field-selector metadata.namespace!=kube-system -o name | grep -cE 'capi|capk|capo|cacppt|cabpt') running"
echo "  XRDs:            $(kubectl get xrd --no-headers 2>/dev/null | wc -l | tr -d ' ') established (cluster-management + AI + Robotics)"
echo ""
echo "  Next steps:"
echo "    1. Add workload cluster kubeconfig as secret in ok-mgmt"
echo "    2. Deploy Open WebUI: kubectl apply -f platform/ai/open-webui/crossplane/examples/<cluster>.yaml"
echo "    3. Submit a cluster claim: kubectl apply -f platform/cluster-management/crossplane/examples/<cluster>.yaml"
echo "    4. Register workload clusters: make register-cluster CLUSTER=<name>"
echo "    5. Apply OpenClawClaim where required: kubectl apply -f platform/ai/openclaw/crossplane/examples/<cluster>.yaml"
echo "    6. Create rmf-credentials Secret, then apply OpenRMFClaim: kubectl apply -f platform/robotics/open-rmf/crossplane/examples/<cluster>.yaml"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
