#!/usr/bin/env bash
# new-cluster.sh — scaffold a new cluster-config.yaml and render initial manifests
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CLUSTER="${CLUSTER:-}"
TYPE="${TYPE:-ubuntu}"
HA="${HA:-false}"
WORKERS="${WORKERS:-1}"
K8S_VERSION="${K8S_VERSION:-v1.34.1}"
TALOS_VERSION="${TALOS_VERSION:-v1.13.4}"
CP_CORES="${CP_CORES:-2}"
CP_MEMORY="${CP_MEMORY:-4Gi}"
WORKER_CORES="${WORKER_CORES:-2}"
WORKER_MEMORY="${WORKER_MEMORY:-4Gi}"
WORKER_DISK="${WORKER_DISK:-15Gi}"
NODE_SELECTOR="${NODE_SELECTOR:-}"

if [[ -z "$CLUSTER" ]]; then
  echo "ERROR: CLUSTER is required."
  exit 1
fi

# Talos requires a nodeSelector for local-path PVC binding
if [[ "$TYPE" == "talos" && -z "$NODE_SELECTOR" ]]; then
  NODE_SELECTOR="ok-gpu"
  echo "  INFO: Talos requires nodeSelector for PVC binding, defaulting to ok-gpu"
fi

CLUSTER_DIR="${SCRIPT_DIR}/${CLUSTER}"
CFG="${CLUSTER_DIR}/cluster-config.yaml"

if [[ -d "$CLUSTER_DIR" ]]; then
  echo "ERROR: Cluster '${CLUSTER}' already exists. Use 'make clean CLUSTER=${CLUSTER}' first."
  exit 1
fi

mkdir -p "$CLUSTER_DIR"

CP_REPLICAS=1
[[ "$HA" == "true" ]] && CP_REPLICAS=3

NEXT_IP=$(python3 "${SCRIPT_DIR}/render.py" next-ip --cluster "${CLUSTER}" 2>/dev/null || echo "auto")
NODE_DISPLAY="${NODE_SELECTOR:-any}"

echo "Creating cluster: ${CLUSTER}"
echo "  type=${TYPE}  HA=${HA}  cp=${CP_REPLICAS}  workers=${WORKERS}  next-ip=${NEXT_IP}  node=${NODE_DISPLAY}"

cat > "$CFG" <<YAML
# OpenKubes cluster config — generated by new-cluster.sh
name: ${CLUSTER}
type: ${TYPE}

controlPlane:
  replicas: ${CP_REPLICAS}
  cores: ${CP_CORES}
  memory: ${CP_MEMORY}

workers:
  replicas: ${WORKERS}
  cores: ${WORKER_CORES}
  memory: ${WORKER_MEMORY}
  disk: ${WORKER_DISK}

versions:
  kubernetes: ${K8S_VERSION}
$(if [[ "$TYPE" == "talos" ]]; then echo "  talos: ${TALOS_VERSION}"; fi)

network:
  endpoint: auto
  podCIDR: auto
  serviceCIDR: auto

nodeSelector: "${NODE_SELECTOR}"

upgrade:
  strategy: blue-green
  workloadMigration:
    stateless: gitops
    stateful: app-native
YAML

echo "  ✔ ${CFG}"
echo ""
echo "Rendering manifests..."
python3 "${SCRIPT_DIR}/render.py" render --cluster "${CLUSTER}"

echo ""
echo "Done. Next steps:"
if [[ "$TYPE" == "talos" ]]; then
  echo "  make bootstrap CLUSTER=${CLUSTER}"
else
  echo "  make install CLUSTER=${CLUSTER}"
fi
