#!/usr/bin/env bash
# generate-manifest.sh — Re-render manifests for ${CLUSTER_NAME} from cluster-config.yaml
# Generated by render.py
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$${SCRIPT_DIR}/../.." && pwd)"

echo "Re-rendering manifests for cluster: ${CLUSTER_NAME}"
python3 "$${ROOT_DIR}/render.py" render --cluster "${CLUSTER_NAME}"
echo "Done."
