controlPlane:
  cores: 2
  disk: 20Gi
  memory: 4Gi
  replicas: 1
name: ok128-talos
network:
  endpoint: 192.168.100.213
  podCIDR: 10.37.0.0/16
  serviceCIDR: 10.96.80.0/20
nodeSelector: ok-infra
os:
  architecture: amd64
  distribution: ok-linux
  goldenImage:
    namespace: ok-images
    claim: talos-v1-9-5-ce4c980550dd-9bb07c3a5857-amd64
    published: true
    storageClass: ok-storage-block
  identity: sha256:62a75f2e872a386ee70fe27158b6e235515d7c0a73f28ce8d95a8547236f1495
  imageDigest: sha256:9bb07c3a585745dd888f6f30f3c5df9c69bf6752171a3058f84ad2ed11dec4f7
  profile: kubevirt
  schematic_id: ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
type: talos
upgrade:
  strategy: blue-green
  workloadMigration:
    stateful: app-native
    stateless: gitops
versions:
  kubernetes: v1.34.1
  talos: v1.9.5
workers:
  cores: 2
  disk: 20Gi
  memory: 4Gi
  replicas: 1
