---
apiVersion: v1
kind: Namespace
metadata:
  name: ok128-talos
  labels:
    openkubes.io/type: talos
    openkubes.io/provider: kubevirt
    openkubes.io/os-identity: 62a75f2e872a
  annotations:
    openkubes.io/os-identity-full: sha256:62a75f2e872a386ee70fe27158b6e235515d7c0a73f28ce8d95a8547236f1495
    openkubes.io/os-image-digest: sha256:9bb07c3a585745dd888f6f30f3c5df9c69bf6752171a3058f84ad2ed11dec4f7
    openkubes.io/golden-image-published: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ok128-talos-talos-golden-image-cloner
  namespace: ok-images
  labels:
    openkubes.io/type: talos
    openkubes.io/consumer-cluster: ok128-talos
    openkubes.io/os-identity: 62a75f2e872a
rules:
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - datavolumes/source
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ok128-talos-talos-golden-image-cloner
  namespace: ok-images
  labels:
    openkubes.io/type: talos
    openkubes.io/consumer-cluster: ok128-talos
    openkubes.io/os-identity: 62a75f2e872a
subjects:
- kind: ServiceAccount
  name: default
  namespace: ok128-talos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ok128-talos-talos-golden-image-cloner
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: ok128-talos
  namespace: ok128-talos
  labels:
    openkubes.io/type: talos
    openkubes.io/provider: kubevirt
    openkubes.io/k8s-version: v1.34.1
    openkubes.io/talos-version: v1.9.5
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.37.0.0/16
    services:
      cidrBlocks:
      - 10.96.80.0/20
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: TalosControlPlane
    name: ok128-talos-cp
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: KubevirtCluster
    name: ok128-talos
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  name: ok128-talos
  namespace: ok128-talos
spec:
  controlPlaneServiceTemplate:
    spec:
      type: LoadBalancer
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: ok128-talos-cp
  namespace: ok128-talos
spec:
  version: v1.34.1
  replicas: 1
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KubevirtMachineTemplate
    name: ok128-talos-cp-62a75f2e872a
    namespace: ok128-talos
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.9.5
      configPatches:
      - op: add
        path: /cluster/network/cni
        value:
          name: none
      - op: add
        path: /cluster/proxy
        value:
          disabled: true
      - op: add
        path: /machine/features/hostDNS
        value:
          enabled: false
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: ok128-talos-workers
  namespace: ok128-talos
spec:
  template:
    spec:
      generateType: worker
      talosVersion: v1.9.5
      configPatches:
      - op: add
        path: /cluster/network/cni
        value:
          name: none
      - op: add
        path: /cluster/proxy
        value:
          disabled: true
      - op: add
        path: /machine/features/hostDNS
        value:
          enabled: false
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: ok128-talos-workers
  namespace: ok128-talos
spec:
  clusterName: ok128-talos
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: ok128-talos
  template:
    spec:
      clusterName: ok128-talos
      version: v1.34.1
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: TalosConfigTemplate
          name: ok128-talos-workers
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: KubevirtMachineTemplate
        name: ok128-talos-workers-62a75f2e872a
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: ok128-talos-cp-62a75f2e872a
  namespace: ok128-talos
  labels:
    openkubes.io/type: talos
    openkubes.io/os-identity: 62a75f2e872a
  annotations:
    openkubes.io/os-identity-full: sha256:62a75f2e872a386ee70fe27158b6e235515d7c0a73f28ce8d95a8547236f1495
    openkubes.io/os-image-digest: sha256:9bb07c3a585745dd888f6f30f3c5df9c69bf6752171a3058f84ad2ed11dec4f7
spec:
  template:
    spec:
      virtualMachineTemplate:
        metadata:
          namespace: ok128-talos
        spec:
          runStrategy: Always
          template:
            spec:
              nodeSelector:
                kubernetes.io/hostname: ok-infra
              domain:
                cpu:
                  cores: 2
                devices:
                  disks:
                  - disk:
                      bus: virtio
                    name: talos
                  networkInterfaceMultiqueue: true
                memory:
                  guest: 4Gi
              evictionStrategy: External
              volumes:
              - dataVolume:
                  name: ok128-talos-cp-62a75f2e872a-disk
                name: talos
          dataVolumeTemplates:
          - metadata:
              name: ok128-talos-cp-62a75f2e872a-disk
              namespace: ok128-talos
            spec:
              pvc:
                accessModes:
                - ReadWriteOnce
                resources:
                  requests:
                    storage: 20Gi
                storageClassName: ok-storage-block
              source:
                pvc:
                  namespace: ok-images
                  name: talos-v1-9-5-ce4c980550dd-9bb07c3a5857-amd64
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: ok128-talos-workers-62a75f2e872a
  namespace: ok128-talos
  labels:
    openkubes.io/type: talos
    openkubes.io/os-identity: 62a75f2e872a
  annotations:
    openkubes.io/os-identity-full: sha256:62a75f2e872a386ee70fe27158b6e235515d7c0a73f28ce8d95a8547236f1495
    openkubes.io/os-image-digest: sha256:9bb07c3a585745dd888f6f30f3c5df9c69bf6752171a3058f84ad2ed11dec4f7
spec:
  template:
    spec:
      virtualMachineTemplate:
        metadata:
          namespace: ok128-talos
        spec:
          runStrategy: Always
          template:
            spec:
              nodeSelector:
                kubernetes.io/hostname: ok-infra
              domain:
                cpu:
                  cores: 2
                devices:
                  disks:
                  - disk:
                      bus: virtio
                    name: talos
                  networkInterfaceMultiqueue: true
                memory:
                  guest: 4Gi
              evictionStrategy: External
              volumes:
              - dataVolume:
                  name: ok128-talos-worker-62a75f2e872a-disk
                name: talos
          dataVolumeTemplates:
          - metadata:
              name: ok128-talos-worker-62a75f2e872a-disk
              namespace: ok128-talos
            spec:
              pvc:
                accessModes:
                - ReadWriteOnce
                resources:
                  requests:
                    storage: 20Gi
                storageClassName: ok-storage-block
              source:
                pvc:
                  namespace: ok-images
                  name: talos-v1-9-5-ce4c980550dd-9bb07c3a5857-amd64
