#!/usr/bin/env bash
# generate-manifest.sh — Re-render manifests for ok128-talos from cluster-config.yaml
# Generated by render.py
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"

echo "Re-rendering manifests for cluster: ok128-talos"
python3 "${ROOT_DIR}/render.py" render --cluster "ok128-talos"
echo "Done."
