#!/usr/bin/env bash
# bootstrap.sh — Talos cluster bootstrap for ok-robotics
# Generated by render.py from cluster-config.yaml
set -euo pipefail

CLUSTER="ok-robotics"
ENDPOINT="192.168.100.208"
K8S_VERSION="v1.34.1"
TALOS_VERSION="v1.9.5"
TALOSCONFIG="${HOME}/.talos/config"
KUBECONFIG_OUT="${HOME}/.kube/ok-robotics.yaml"

echo "═══════════════════════════════════════════════════════════"
echo "  Bootstrapping Talos cluster: ${CLUSTER}"
echo "  Endpoint: ${ENDPOINT}  K8s: ${K8S_VERSION}  Talos: ${TALOS_VERSION}"
echo "═══════════════════════════════════════════════════════════"

# 1. Apply CAPI manifests to management cluster
echo ""
echo "── Step 1: Apply CAPI manifests ──"
okm apply -f "$(dirname "$0")/cluster-base.yaml"
okm apply -f "$(dirname "$0")/cluster-v2.yaml"

# 2. Wait for control plane
echo ""
echo "── Step 2: Wait for control plane VMs ──"
okm wait cluster/${CLUSTER} --for=condition=ControlPlaneReady --timeout=15m -n default

# 3. Retrieve Talos endpoint IP from MetalLB LB service
echo ""
echo "── Step 3: Get Talos endpoint ──"
TALOS_EP=$(okm get svc ${CLUSTER}-lb -n default -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || echo "${ENDPOINT}")
echo "  Talos endpoint: ${TALOS_EP}"

# 4. Generate and apply Talos config
echo ""
echo "── Step 4: Generate Talos config ──"
mkdir -p /tmp/talos-${CLUSTER}
talosctl gen config ${CLUSTER} "https://${TALOS_EP}:6443" \
  --output-dir /tmp/talos-${CLUSTER} \
  --with-cluster-discovery=false \
  --kubernetes-version v1.34.1

talosctl apply-config \
  --insecure \
  --nodes ${TALOS_EP} \
  --file /tmp/talos-${CLUSTER}/controlplane.yaml

# 5. Bootstrap etcd
echo ""
echo "── Step 5: Bootstrap etcd ──"
talosctl bootstrap \
  --talosconfig /tmp/talos-${CLUSTER}/talosconfig \
  --nodes ${TALOS_EP}

# 6. Retrieve kubeconfig
echo ""
echo "── Step 6: Retrieve kubeconfig ──"
talosctl kubeconfig \
  --talosconfig /tmp/talos-${CLUSTER}/talosconfig \
  --nodes ${TALOS_EP} \
  --merge=false \
  "${KUBECONFIG_OUT}"

echo ""
echo "✅ Done. Test: kubectl --kubeconfig ${KUBECONFIG_OUT} get nodes"
