---
apiVersion: v1
kind: Namespace
metadata:
  name: ok-iot
  labels:
    openkubes.io/type: talos
    openkubes.io/provider: kubevirt
    openkubes.io/os-identity: 7f5dd4276432
  annotations:
    openkubes.io/os-identity-full: sha256:7f5dd4276432f522727a50e604538b6befc0cac51ee2b90d4b1ccbfcac774a2d
    openkubes.io/os-image-digest: sha256:461d72d30750b9e18cf0656239e0274764b1e391bde5bbc41084a887b8a55ed5
    openkubes.io/golden-image-published: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ok-iot-talos-golden-image-cloner
  namespace: ok-images
  labels:
    openkubes.io/type: talos
    openkubes.io/consumer-cluster: ok-iot
    openkubes.io/os-identity: 7f5dd4276432
rules:
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - datavolumes/source
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ok-iot-talos-golden-image-cloner
  namespace: ok-images
  labels:
    openkubes.io/type: talos
    openkubes.io/consumer-cluster: ok-iot
    openkubes.io/os-identity: 7f5dd4276432
subjects:
- kind: ServiceAccount
  name: default
  namespace: ok-iot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ok-iot-talos-golden-image-cloner
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: ok-iot
  namespace: ok-iot
  labels:
    openkubes.io/type: talos
    openkubes.io/provider: kubevirt
    openkubes.io/k8s-version: v1.34.1
    openkubes.io/talos-version: v1.9.6
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.36.0.0/16
    services:
      cidrBlocks:
      - 10.96.64.0/20
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: TalosControlPlane
    name: ok-iot-cp
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: KubevirtCluster
    name: ok-iot
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  name: ok-iot
  namespace: ok-iot
spec:
  controlPlaneServiceTemplate:
    spec:
      type: LoadBalancer
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: ok-iot-cp
  namespace: ok-iot
spec:
  version: v1.34.1
  replicas: 1
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KubevirtMachineTemplate
    name: ok-iot-cp-7f5dd4276432-dc9767fa
    namespace: ok-iot
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.9.6
      configPatches:
      - op: add
        path: /cluster/network/cni
        value:
          name: none
      - op: add
        path: /cluster/proxy
        value:
          disabled: true
      - op: add
        path: /machine/features/hostDNS
        value:
          enabled: false
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: ok-iot-workers-v1-9-6
  namespace: ok-iot
spec:
  template:
    spec:
      generateType: worker
      talosVersion: v1.9.6
      configPatches:
      - op: add
        path: /cluster/network/cni
        value:
          name: none
      - op: add
        path: /cluster/proxy
        value:
          disabled: true
      - op: add
        path: /machine/features/hostDNS
        value:
          enabled: false
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: ok-iot-workers
  namespace: ok-iot
spec:
  clusterName: ok-iot
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: ok-iot
  template:
    spec:
      clusterName: ok-iot
      version: v1.34.1
      bootstrap:
          configRef:
            apiGroup: bootstrap.cluster.x-k8s.io
            kind: TalosConfigTemplate
            name: ok-iot-workers-v1-9-6
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: KubevirtMachineTemplate
        name: ok-iot-workers-7f5dd4276432-dc9767fa
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: ok-iot-cp-7f5dd4276432-dc9767fa
  namespace: ok-iot
  labels:
    openkubes.io/type: talos
    openkubes.io/os-identity: 7f5dd4276432
  annotations:
    openkubes.io/os-identity-full: sha256:7f5dd4276432f522727a50e604538b6befc0cac51ee2b90d4b1ccbfcac774a2d
    openkubes.io/os-image-digest: sha256:461d72d30750b9e18cf0656239e0274764b1e391bde5bbc41084a887b8a55ed5
    openkubes.io/provider-profile: ok-gpu
    openkubes.io/provider-profile-identity: sha256:dc9767fa3ff70c232f892ed5a999bbe998fcc08b099a736f4486600a04181226
spec:
  template:
    spec:
      virtualMachineTemplate:
        metadata:
          namespace: ok-iot
        spec:
          runStrategy: Always
          template:
            spec:
              nodeSelector:
                kubernetes.io/hostname: ok-gpu
              domain:
                cpu:
                  cores: 2
                devices:
                  disks:
                  - disk:
                      bus: virtio
                    name: talos
                  networkInterfaceMultiqueue: true
                memory:
                  guest: 4Gi
              evictionStrategy: External
              volumes:
              - dataVolume:
                  name: ok-iot-cp-7f5dd4276432-dc9767fa-disk
                name: talos
          dataVolumeTemplates:
          - metadata:
              name: ok-iot-cp-7f5dd4276432-dc9767fa-disk
              namespace: ok-iot
            spec:
              pvc:
                accessModes:
                - ReadWriteOnce
                resources:
                  requests:
                    storage: 20Gi
                storageClassName: ok-storage-block
              source:
                pvc:
                  namespace: ok-images
                  name: talos-v1-9-6-ce4c980550dd-461d72d30750-amd64
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: ok-iot-workers-7f5dd4276432-dc9767fa
  namespace: ok-iot
  labels:
    openkubes.io/type: talos
    openkubes.io/os-identity: 7f5dd4276432
  annotations:
    openkubes.io/os-identity-full: sha256:7f5dd4276432f522727a50e604538b6befc0cac51ee2b90d4b1ccbfcac774a2d
    openkubes.io/os-image-digest: sha256:461d72d30750b9e18cf0656239e0274764b1e391bde5bbc41084a887b8a55ed5
    openkubes.io/provider-profile: ok-gpu
    openkubes.io/provider-profile-identity: sha256:dc9767fa3ff70c232f892ed5a999bbe998fcc08b099a736f4486600a04181226
spec:
  template:
    spec:
      virtualMachineTemplate:
        metadata:
          namespace: ok-iot
        spec:
          runStrategy: Always
          template:
            spec:
              nodeSelector:
                kubernetes.io/hostname: ok-gpu
              domain:
                cpu:
                  cores: 4
                devices:
                  disks:
                  - disk:
                      bus: virtio
                    name: talos
                  networkInterfaceMultiqueue: true
                memory:
                  guest: 8Gi
              evictionStrategy: External
              volumes:
              - dataVolume:
                  name: ok-iot-worker-7f5dd4276432-dc9767fa-disk
                name: talos
          dataVolumeTemplates:
          - metadata:
              name: ok-iot-worker-7f5dd4276432-dc9767fa-disk
              namespace: ok-iot
            spec:
              pvc:
                accessModes:
                - ReadWriteOnce
                resources:
                  requests:
                    storage: 30Gi
                storageClassName: ok-storage-block
              source:
                pvc:
                  namespace: ok-images
                  name: talos-v1-9-6-ce4c980550dd-461d72d30750-amd64
