#!/usr/bin/env bash
# bootstrap-mgmt.sh — OpenKubes Management Cluster Bootstrap
# Generated by ok-cluster from templates/talos-mgmt/bootstrap-mgmt.sh.tpl
#
# This script installs the full OpenKubes management stack on ok-mgmt:
#   1. Crossplane
#   2. Crossplane Providers (kubernetes, helm)
#   3. Crossplane Functions (patch-and-transform, go-templating)
#   4. CAPI + CAPK + Talos providers (via clusterctl)
#   5. XRDs + Compositions (from openkubes/openkubes)
#   6. XRDs + Compositions (cluster-management)
#   7. RBAC for Crossplane provider ServiceAccounts
#   8. OpenWebUI XRD + Composition (platform/ai)
#
# Run after: make bootstrap CLUSTER=${CLUSTER_NAME}
# Context:   KUBECONFIG must point to the management cluster
#
# See: ok-cluster ADR-Platform-008 — TYPE=talos-mgmt
#      ok-cluster ADR-Platform-007 — CAPI responsibility split

set -euo pipefail

CLUSTER_NAME="${CLUSTER_NAME:-${CLUSTER_NAME}}"
KUBECONFIG_PATH="${KUBECONFIG:-$$HOME/.kube/${CLUSTER_NAME}.yaml}"
OPENKUBES_REPO="${OPENKUBES_PATH:-$$(dirname "$$0")/../../openkubes}"

log()  { echo "[mgmt-bootstrap] $$*"; }
ok()   { echo "[mgmt-bootstrap] ✅ $$*"; }
fail() { echo "[mgmt-bootstrap] ❌ $$*" >&2; exit 1; }

export KUBECONFIG="$$KUBECONFIG_PATH"

log "Bootstrapping OpenKubes management stack on cluster '${CLUSTER_NAME}'..."
log "KUBECONFIG: $$KUBECONFIG_PATH"
echo ""

# ── Verify cluster is reachable ───────────────────────────────────────────────
log "Verifying cluster connectivity..."
kubectl get nodes || fail "Cannot reach management cluster — check KUBECONFIG"
ok "Cluster reachable"
echo ""

# ── Step 1: Crossplane ────────────────────────────────────────────────────────
log "Step 1: Installing Crossplane..."
helm repo add crossplane-stable https://charts.crossplane.io/stable 2>/dev/null || true
helm repo update crossplane-stable

helm upgrade --install crossplane crossplane-stable/crossplane \
  --namespace crossplane-system \
  --create-namespace \
  --wait \
  --timeout 300s

ok "Crossplane installed (version: $$(helm list -n crossplane-system -o json | python3 -c 'import sys,json; print(json.load(sys.stdin)[0]["app_version"])' 2>/dev/null || echo 'unknown'))"
echo ""

# ── Step 2: Crossplane Providers ──────────────────────────────────────────────
log "Step 2: Installing Crossplane Providers (kubernetes, helm)..."

kubectl apply -f - <<YAML
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-contrib-provider-kubernetes
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.14.1
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-contrib-provider-helm
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.19.0
YAML

log "Waiting for providers to become healthy..."
kubectl wait provider/crossplane-contrib-provider-kubernetes \
  --for=condition=Healthy --timeout=300s
kubectl wait provider/crossplane-contrib-provider-helm \
  --for=condition=Healthy --timeout=300s

ok "Providers installed and healthy"
echo ""

# ── Step 3: Crossplane Functions ──────────────────────────────────────────────
log "Step 3: Installing Crossplane Functions..."

kubectl apply -f - <<YAML
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.9.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-go-templating
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.9.0
YAML

log "Waiting for functions to become healthy..."
kubectl wait function/function-patch-and-transform \
  --for=condition=Healthy --timeout=300s
kubectl wait function/function-go-templating \
  --for=condition=Healthy --timeout=300s

ok "Functions installed and healthy"
echo ""

# ── Step 4: CAPI + Talos + KubeVirt providers ────────────────────────────────
log "Step 4: Installing CAPI providers (core, talos, kubevirt)..."

clusterctl init \
  --infrastructure kubevirt \
  --bootstrap talos \
  --control-plane talos

log "Waiting for CAPI pods to be ready..."
kubectl wait deployment/capi-controller-manager \
  -n capi-system --for=condition=Available --timeout=300s
kubectl wait deployment/capk-controller-manager \
  -n capk-system --for=condition=Available --timeout=300s
kubectl wait deployment/cacppt-controller-manager \
  -n cacppt-system --for=condition=Available --timeout=300s

ok "CAPI providers installed"
echo ""

# ── Step 5: ok-infra kubeconfig secret for CAPK ───────────────────────────────
log "Step 5: Creating ok-infra kubeconfig secret for CAPK..."
INFRA_KUBECONFIG="${INFRA_KUBECONFIG_PATH:-$$HOME/.kube/ok-infra.yaml}"

if [[ ! -f "$$INFRA_KUBECONFIG" ]]; then
  fail "ok-infra kubeconfig not found at $$INFRA_KUBECONFIG — set INFRA_KUBECONFIG_PATH"
fi

kubectl -n capk-system create secret generic external-infra-kubeconfig \
  --from-file=kubeconfig="$$INFRA_KUBECONFIG" \
  --dry-run=client -o yaml | kubectl apply -f -

kubectl -n capk-system rollout restart deployment/capk-controller-manager
kubectl -n capk-system rollout status deployment/capk-controller-manager --timeout=120s

ok "ok-infra kubeconfig secret created"
echo ""

# ── Step 6: XRDs + Compositions + RBAC ────────────────────────────────────────
log "Step 6: Applying OpenKubes platform contracts (XRDs, Compositions, RBAC)..."

PLATFORM_DIR="${OPENKUBES_REPO}/platform/cluster-management"

if [[ ! -d "$$PLATFORM_DIR" ]]; then
  fail "openkubes/openkubes not found at $$OPENKUBES_REPO — set OPENKUBES_PATH"
fi

kubectl apply -f "$$PLATFORM_DIR/crossplane/namespace.yaml"
kubectl apply -f "$$PLATFORM_DIR/crossplane/rbac.yaml"
kubectl apply -f "$$PLATFORM_DIR/crossplane/xrd.yaml"
kubectl apply -f "$$PLATFORM_DIR/crossplane/xrd-cleanup.yaml"
kubectl apply -f "$$PLATFORM_DIR/crossplane/xrd-upgrade.yaml"
kubectl apply -f "$$PLATFORM_DIR/crossplane/composition.yaml"
kubectl apply -f "$$PLATFORM_DIR/crossplane/composition-cleanup.yaml"
kubectl apply -f "$$PLATFORM_DIR/crossplane/composition-upgrade.yaml"

ok "Platform contracts applied"
echo ""

# ── Step 7: RBAC for Crossplane provider ServiceAccounts ──────────────────────
log "Step 7: Configuring RBAC for Crossplane provider..."

# Resolve the dynamic ServiceAccount name for provider-kubernetes
PROVIDER_SA=$$(kubectl get serviceaccount -n crossplane-system \
  -o jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | \
  grep "crossplane-contrib-provider-kubernetes" | head -1)

if [[ -z "$$PROVIDER_SA" ]]; then
  fail "Cannot find provider-kubernetes ServiceAccount in crossplane-system"
fi

log "Provider ServiceAccount: $$PROVIDER_SA"

kubectl apply -f - <<YAML
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-provider-kubernetes-jobs
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps", "serviceaccounts"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-provider-kubernetes-jobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-provider-kubernetes-jobs
subjects:
  - kind: ServiceAccount
    name: $$PROVIDER_SA
    namespace: crossplane-system
YAML

# ProviderConfig for in-cluster access
kubectl apply -f - <<YAML
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: in-cluster
spec:
  credentials:
    source: InjectedIdentity
YAML

ok "RBAC configured"
echo ""

# ── Step 8: OpenWebUI XRD + Composition ──────────────────────────────────────
log "Step 8: Applying OpenWebUI platform contracts (XRD, Composition)..."

OPENKUBES_AI_DIR="${OPENKUBES_REPO}/platform/ai/open-webui/crossplane"

if [[ ! -d "$$OPENKUBES_AI_DIR" ]]; then
  log "WARNING: platform/ai not found at $$OPENKUBES_AI_DIR — skipping OpenWebUI setup"
else
  kubectl apply -f "$$OPENKUBES_AI_DIR/xrd.yaml"
  kubectl apply -f "$$OPENKUBES_AI_DIR/composition.yaml"

  kubectl wait xrd/openwebuiinstances.platform.openkubes.ai \
    --for=condition=Established --timeout=60s

  ok "OpenWebUI XRD + Composition ready on ok-mgmt"
  log "  Deploy with: kubectl apply -f platform/ai/open-webui/crossplane/examples/<cluster>.yaml"
fi
echo ""

# ── Done ──────────────────────────────────────────────────────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ok "Management cluster '${CLUSTER_NAME}' is fully operational!"
echo ""
echo "  Crossplane:      $$(kubectl get deployment crossplane -n crossplane-system -o jsonpath='{.status.readyReplicas}')/1 ready"
echo "  CAPI providers:  $$(kubectl get deployments -A --field-selector metadata.namespace!=kube-system -o name | grep -cE 'capi|capk|cacppt|cabpt') running"
echo "  XRDs:            $$(kubectl get xrd --no-headers 2>/dev/null | wc -l | tr -d ' ') established (cluster-management + AI)"
echo ""
echo "  Next steps:"
echo "    1. Add workload cluster kubeconfig as secret in ok-mgmt"
echo "    2. Deploy Open WebUI: kubectl apply -f platform/ai/open-webui/crossplane/examples/<cluster>.yaml"
echo "    3. Submit a KubeVirtClusterClaim: kubectl apply -f crossplane/examples/ok1-talos.yaml"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
